apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zigbee2mqtt-manifests
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
rules:
  - apiGroups:  ["*"]
    resources:  ["*"]
    verbs:  ["*"]