nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

securityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

persistent:
  enabled: false
  existantPVCname: ""
  storageClass: ""
  capacity: 2Gi
  accessModes:
    - ReadWriteOnce

zigbee2mqtt:
  deployment:
    replicaCount: 1
    debug: false
    strategy:
      type: Recreate
    labels: {}
    annotations: {}
    podSecurityContext:
      privileged: true
      readOnlyRootFilesystem: false
      capabilities:
        drop:
        - ALL
    imagePullSecrets: []
    image:
      repository: koenkk/zigbee2mqtt
      pullPolicy: IfNotPresent
      tag: ""
    frontend:
      enabled: true
      port: 8080
    env: []
    configuration:
      homeassistant: "false"
      permitjoin: "false"
      baseTopicName: "zigbee2mqtt"
      mqttServerName: "mqtt://localhost:1883"
      serialport: "/dev/ttyACM0"
      panid: ""
    devicePath: /dev/ttyUSB0
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
  service:
    type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: zigbee2mqtt.hostname
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local









