apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
data:
  initconfig.sh: |
    #!/bin/sh
    
    DAPAPATH="/app/data"
    CONFIGFILE="configuration.yaml"
    FULLCONFIGPATH="${DAPAPATH}/${CONFIGFILE}"
    
    if [ -f ${DAPAPATH}/yq/yq_linux_amd64 ]; then
      echo "YQ installed"
    else
      mkdir ${DAPAPATH}/yq
      wget  -O ${DAPAPATH}/yq/yq.tar.gz https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64.tar.gz
      cd ${DAPAPATH}/yq
      tar xvf ./yq.tar.gz ./yq_linux_amd64
      rm -rf yq.tar.gz
    fi
    
    setconfvar() {
        local param=$1 variable=$2
        if [ ${variable} = "true" ] || [ ${variable} = "false" ]; then
          echo "Set ${param}=${variable} ${FULLCONFIGPATH}"
          ${DAPAPATH}/yq/yq_linux_amd64 e ${param}=${variable} -i ${FULLCONFIGPATH}
        else
          echo "Set ${param}=\"${variable}\" ${FULLCONFIGPATH}"
          ${DAPAPATH}/yq/yq_linux_amd64 e ${param}=\"${variable}\" -i ${FULLCONFIGPATH}
        fi
    }
    
    setupconfigfile() {
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_HOMEASSISTANT} ]; then
        setconfvar ".homeassistant" "${ZIGBEE2MQTT_CONFIG_HOMEASSISTANT}"
      fi
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_PERMITJOIN} ]; then
        setconfvar ".permit_join" "${ZIGBEE2MQTT_CONFIG_PERMITJOIN}"
      fi
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_MQTT_BASETOPIC} ]; then
        setconfvar ".mqtt.base_topic" "${ZIGBEE2MQTT_CONFIG_MQTT_BASETOPIC}"
      fi
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_MQTT_SERVER} ]; then
        setconfvar ".mqtt.server" "${ZIGBEE2MQTT_CONFIG_MQTT_SERVER}"
      fi
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_SERIAL_PORT} ]; then
        setconfvar ".server.port" "${ZIGBEE2MQTT_CONFIG_SERIAL_PORT}"
      fi
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_FRONTEND_PORT} ]; then
        setconfvar ".frontend.port" "$ZIGBEE2MQTT_CONFIG_FRONTEND_PORT"
      fi
    }
    
    if [ -f "${FULLCONFIGPATH}" ]; then
        echo "File ${FULLCONFIGPATH} exist "
        echo "Set config paramert from ENV variables"
        setupconfigfile
    else
      echo "File ${FULLCONFIGPATH} not exist"
      echo "Create ${FULLCONFIGPATH} file"
      touch ${FULLCONFIGPATH}
      setupconfigfile
      if [ ! -z ${ZIGBEE2MQTT_CONFIG_ADVANCED_PANID} ]; then
        setconfvar ".advanced.pan_id" "GENERATE"
      fi
    fi
    cd /app
    node index.js