{{- if .Values.zigbee2mqtt.deployment.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zigbee2mqtt.frontend.service.name" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zigbee2mqtt.service.type }}
  ports:
    - port: {{ .Values.zigbee2mqtt.deployment.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zigbee2mqtt.selectorLabels" . | nindent 4 }}
{{- end }}